# Generated by Django 3.1 on 2020-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='followings',
            field=models.IntegerField(default=0),
        ),
    ]
