# Generated by Django 3.1 on 2020-10-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('listings', '0002_listing_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
    ]
