# Generated by Django 3.1 on 2020-09-28 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
                ('listing_id', models.IntegerField()),
                ('listing', models.CharField(max_length=200)),
            ],
        ),
    ]
